# Generated by Django 4.2.3 on 2023-07-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField(verbose_name="Цена")),
                ("image", models.ImageField(upload_to="", verbose_name="Изображение")),
                ("release_date", models.DateField()),
                ("lte_exists", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, unique=True, verbose_name="URL")),
            ],
        ),
    ]
